### ISSUE TITLE
Add `7d` weekly duration queries

### ISSUE THREAD

**Issue by DenisCarriere** [defiboxswap/eosio.yield-api#3]
- [ ] Attribute can be `week` or `7d`

<img width="448" alt="image" src="https://user-images.githubusercontent.com/550895/180820386-a1a3cf9e-6621-47a1-8868-57d18d4aa150.png">

**Comment by DenisCarriere** [comment]
Ref: https://github.com/defiboxswap/eosio.yield-ui/issues/13

**Comment by YaCoHuang** [comment]
[Add interface to return SVG](https://dev.api.tokenyield.io/v1/protocols/swap.defi/sparkline?tvl_type=tvl_usd)
![image](https://user-images.githubusercontent.com/18477505/181726909-71bc1603-0ee2-4ed2-96a9-e0109f49d069.png)

**Comment by DenisCarriere** [comment]
Awesome! Looks great 💪

**Comment by DenisCarriere** [comment]
Implemented

<img width="439" alt="image" src="https://user-images.githubusercontent.com/550895/181832303-55d1966c-1f47-4c18-9e5e-074bcecddfb8.png">
