### ISSUE TITLE
Uploading image - CORS issue or Error 500

### ISSUE THREAD

**Issue by DenisCarriere** [defiboxswap/eosio.yield-api#7]
## Image to upload
<img width="134" alt="Screen Shot 2022-08-08 at 12 55 56 PM" src="https://user-images.githubusercontent.com/550895/183472774-e4e9ebc6-7d5d-4798-913e-5682cae7b2a1.png">

## Errors

<img width="955" alt="image" src="https://user-images.githubusercontent.com/550895/183472630-db9962d7-341b-4c82-81ce-c86c1de82517.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/550895/183472761-98a924d5-23fb-4b46-9ba0-e536472dd05b.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/550895/183473445-ca8c68c9-9682-4401-a299-c8ad682b62ee.png">

**Comment by YaCoHuang** [comment]
Fixed because temporary folder does not have permissions.
